[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Peripheral access API for STM32F30X microcontrollers"
documentation = "https://docs.rs/stm32f30x"
keywords = ["arm", "cortex-m", "stm32", "svd2rust"]
license = "MIT OR Apache-2.0"
name = "stm32f30x"
repository = "https://github.com/japaric/stm32f30x"
version = "0.5.0"

[dependencies]
bare-metal = "0.1.0"
cortex-m = "0.3.1"
vcell = "0.1.0"
